In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
color = sns.color_palette()
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
aisles_df=pd.read_csv("aisles.csv")
products_df=pd.read_csv("products.csv")
departments_df=pd.read_csv("departments.csv")
orders_df=pd.read_csv("orders.csv")
order_products_prior_df=pd.read_csv("order_products__prior.csv")
order_products_train_df=pd.read_csv("order_products__train.csv")

In [ ]:
order_products_prior_df = pd.merge(order_products_prior_df, products_df, on='product_id', how='left')
order_products_prior_df = pd.merge(order_products_prior_df, aisles_df, on='aisle_id', how='left')
order_products_prior_df = pd.merge(order_products_prior_df, departments_df, on='department_id', how='left')
order_products_prior_df.head()

   order_id  product_id  ...               aisle  department
0         2       33120  ...                eggs  dairy eggs
1         2       28985  ...    fresh vegetables     produce
2         2        9327  ...   spices seasonings      pantry
3         2       45918  ...       oils vinegars      pantry
4         2       30035  ...  baking ingredients      pantry

[5 rows x 9 columns]

In [ ]:
 order_products_prior_df= order_products_prior_df[order_products_prior_df['order_id']>=50]

In [ ]:
item = order_products_prior_df[['order_id','product_name']].copy()
item.rename(columns={'order_id':'order','product_name':'items'},inplace=True)
item['temp']=1

In [ ]:
df = item.groupby(['order','items'])['temp'].sum().unstack().fillna(0)

In [ ]:
def myencoder(i):
    if i <= 0:
        return 0
    elif i>=1:
        return 1

In [ ]:
df.applymap(myencoder)

Empty DataFrame
Columns: []
Index: []

In [ ]:
freq_itemsets = apriori(df,min_support=0.01,use_colnames=True)
freq_itemsets

Empty DataFrame
Columns: [support, itemsets]
Index: []

In [ ]:
rules = association_rules(freq_itemsets,metric='lift',min_threshold=1)
rules.sort_values(by='confidence',ascending=False)

                 antecedents               consequents  ...  leverage  conviction
9         (Honeycrisp Apple)                  (Banana)  ...  0.006244    1.384749
14      (Organic Fuji Apple)                  (Banana)  ...  0.006187    1.347210
4      (Organic Raspberries)  (Bag of Organic Bananas)  ...  0.007747    1.257173
2     (Organic Hass Avocado)  (Bag of Organic Bananas)  ...  0.011489    1.252481
21            (Strawberries)                  (Banana)  ...  0.006775    1.211503
11         (Organic Avocado)                  (Banana)  ...  0.007303    1.182641
26     (Organic Raspberries)    (Organic Strawberries)  ...  0.006660    1.201893
19    (Organic Strawberries)                  (Banana)  ...  0.006730    1.110734
1     (Organic Baby Spinach)  (Bag of Organic Bananas)  ...  0.007029    1.123407
7     (Organic Strawberries)  (Bag of Organic Bananas)  ...  0.007615    1.122513
13    (Organic Baby Spinach)                  (Banana)  ...  0.003998    1.069041
24    (Organic Hass Avocado)    (Organic Strawberries)  ...  0.006632    1.125049
17    (Organic Hass Avocado)                  (Banana)  ...  0.001578    1.029468
23    (Organic Baby Spinach)    (Organic Strawberries)  ...  0.006743    1.111926
3   (Bag of Organic Bananas)    (Organic Hass Avocado)  ...  0.011489    1.113418
22    (Organic Strawberries)    (Organic Baby Spinach)  ...  0.006743    1.100911
25    (Organic Strawberries)    (Organic Hass Avocado)  ...  0.006632    1.098154
6   (Bag of Organic Bananas)    (Organic Strawberries)  ...  0.007615    1.073633
0   (Bag of Organic Bananas)    (Organic Baby Spinach)  ...  0.007029    1.067075
27    (Organic Strawberries)     (Organic Raspberries)  ...  0.006660    1.096154
18                  (Banana)    (Organic Strawberries)  ...  0.006730    1.051544
5   (Bag of Organic Bananas)     (Organic Raspberries)  ...  0.007747    1.071958
10                  (Banana)         (Organic Avocado)  ...  0.007303    1.054691
12                  (Banana)    (Organic Baby Spinach)  ...  0.003998    1.029776
20                  (Banana)            (Strawberries)  ...  0.006775    1.049980
16                  (Banana)    (Organic Hass Avocado)  ...  0.001578    1.011447
15                  (Banana)      (Organic Fuji Apple)  ...  0.006187    1.044596
8                   (Banana)        (Honeycrisp Apple)  ...  0.006244    1.044936

[28 rows x 9 columns]

In [ ]:
rules[(rules['lift']>1)]

                 antecedents               consequents  ...  leverage  conviction
0   (Bag of Organic Bananas)    (Organic Baby Spinach)  ...  0.007029    1.067075
1     (Organic Baby Spinach)  (Bag of Organic Bananas)  ...  0.007029    1.123407
2     (Organic Hass Avocado)  (Bag of Organic Bananas)  ...  0.011489    1.252481
3   (Bag of Organic Bananas)    (Organic Hass Avocado)  ...  0.011489    1.113418
4      (Organic Raspberries)  (Bag of Organic Bananas)  ...  0.007747    1.257173
5   (Bag of Organic Bananas)     (Organic Raspberries)  ...  0.007747    1.071958
6   (Bag of Organic Bananas)    (Organic Strawberries)  ...  0.007615    1.073633
7     (Organic Strawberries)  (Bag of Organic Bananas)  ...  0.007615    1.122513
8                   (Banana)        (Honeycrisp Apple)  ...  0.006244    1.044936
9         (Honeycrisp Apple)                  (Banana)  ...  0.006244    1.384749
10                  (Banana)         (Organic Avocado)  ...  0.007303    1.054691
11         (Organic Avocado)                  (Banana)  ...  0.007303    1.182641
12                  (Banana)    (Organic Baby Spinach)  ...  0.003998    1.029776
13    (Organic Baby Spinach)                  (Banana)  ...  0.003998    1.069041
14      (Organic Fuji Apple)                  (Banana)  ...  0.006187    1.347210
15                  (Banana)      (Organic Fuji Apple)  ...  0.006187    1.044596
16                  (Banana)    (Organic Hass Avocado)  ...  0.001578    1.011447
17    (Organic Hass Avocado)                  (Banana)  ...  0.001578    1.029468
18                  (Banana)    (Organic Strawberries)  ...  0.006730    1.051544
19    (Organic Strawberries)                  (Banana)  ...  0.006730    1.110734
20                  (Banana)            (Strawberries)  ...  0.006775    1.049980
21            (Strawberries)                  (Banana)  ...  0.006775    1.211503
22    (Organic Strawberries)    (Organic Baby Spinach)  ...  0.006743    1.100911
23    (Organic Baby Spinach)    (Organic Strawberries)  ...  0.006743    1.111926
24    (Organic Hass Avocado)    (Organic Strawberries)  ...  0.006632    1.125049
25    (Organic Strawberries)    (Organic Hass Avocado)  ...  0.006632    1.098154
26     (Organic Raspberries)    (Organic Strawberries)  ...  0.006660    1.201893
27    (Organic Strawberries)     (Organic Raspberries)  ...  0.006660    1.096154

[28 rows x 9 columns]